// Logic callers retain their API; Words owns the imperative rendering lifecycle.
export {
  updateHintsPositionDebounced,
  activeWordTop,
  activeWordHeight,
  focusWords,
  keepWordsInputInTheCenter,
  getWordElement,
  getActiveWordElement,
  updateActiveElement,
  appendEmptyWordElement,
  updateWordsInputPosition,
  centerActiveLine,
  updateWordsWrapperHeight,
  addWord,
  pendingWordData,
  updateWordLetters,
  scrollTape,
  setJoiningClass,
  highlightBadWord,
  highlightAllLettersAsCorrect,
  getActiveWordTopAndHeightWithDifferentData,
  afterTestTextInput,
  afterTestCompositionUpdate,
  afterTestDelete,
  beforeTestWordChange,
  afterTestWordChange,
  onTestStart,
  fadeOutForRestart,
  fadeInAfterRestart,
  onTestRestart,
  onTestFinish,
} from "../components/pages/test/Words";
