#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ "$(git symbolic-ref --short HEAD)" = "master" ]; then
  case "$(git remote get-url origin)" in
    https://github.com/voltcrash/oxytype|https://github.com/voltcrash/oxytype.git|git@github.com:voltcrash/oxytype.git) ;;
    *) exit 0 ;;
  esac
  npx --no -- commitlint --edit ${1}
fi

