#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"


if [ "$(git symbolic-ref --short HEAD)" = "master" ]; then
  case "$(git remote get-url origin)" in
    https://github.com/voltcrash/oxytype|https://github.com/voltcrash/oxytype.git|git@github.com:voltcrash/oxytype.git) ;;
    *) exit 0 ;;
  esac
  nvm install
  echo "Running a full check before pushing to master..."
  pnpm run full-check
  if [ $? -ne 0 ]; then
    echo "Full check failed, aborting push."
    exit 1
  fi
fi